In [1]:
# Creating arrays filled with constant values
import numpy as np

In [2]:
first_z_element=np.zeros(4)
first_z_element

array([0., 0., 0., 0.])

In [5]:
second_z_element=np.zeros((4,4))
second_z_element

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
first_z_element_with_type=np.zeros(4, dtype='int64')
first_z_element_with_type

print(first_z_element_with_type)

[0 0 0 0]
