In [1]:
#Intrinsic numpy array creation
import numpy as np

In [3]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [5]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [7]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [8]:
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [9]:
First_rand_array = np.random.rand(10)
First_rand_array

array([0.08922298, 0.74142688, 0.72151265, 0.82217219, 0.29356038,
       0.38307737, 0.84596223, 0.66896839, 0.45751326, 0.3319336 ])

In [10]:
second_rand_array = np.random.rand(4,4)
second_rand_array

array([[0.11608422, 0.01849437, 0.71848664, 0.55551694],
       [0.37469404, 0.46078573, 0.73711007, 0.70459945],
       [0.73838737, 0.37180163, 0.03978578, 0.38906598],
       [0.6225769 , 0.7723848 , 0.36380562, 0.9022351 ]])

In [13]:
third_rand_array = np.random.randint(0,100,20)
third_rand_array

array([22, 85, 45, 60, 73, 27, 56, 15, 91, 24,  7, 12, 12, 13, 47, 39, 24,
       54, 14, 88])