In [1]:
import numpy as np

In [16]:
# How to create a basic array

arrayWithoutdType = np.zeros(2)
print(arrayWithoutdType)

arrayWithDataType=np.zeros(2, dtype=np.int64)
print(arrayWithDataType)

print(np.ones(4))


print(np.empty(2))

print(np.linspace(0, 10, num=4, dtype=np.int64))

[0. 0.]
[0 0]
[1. 1. 1. 1.]
[0. 0.]
[ 0  3  6 10]


In [22]:
# Adding Removing Sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

a = np.array([[1,4],[3,1]])

print(np.sort(a))

print(np.sort(a, axis=None)) #sort the flattened array

np.sort(a, axis=0)   #sort along the first axis

np.sort(a, axis=1)

[[1 4]
 [1 3]]
[1 1 3 4]


array([[1, 4],
       [1, 3]])

In [23]:
#Use the order keyword to specify a field to use when sorting a structured array

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

a = np.array(values, dtype=dtype)       # create a structured array
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [24]:
# Sort by age, then height if ages are equal:

np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [ ]:
# numpy.lexsort

